import React from 'react';
import BusinessLoanCard from './BusinessLoanCard';

export default function BusinessLoans() {
  const businessLoansData = [
    {
      id: 1,
      title: 'Արագ բիզնես վարկ/վարկային գիծ',
      description: 'Արագ ֆինանսավորում Ձեր բիզնեսի զարգացման համար միայն երաշխավորությամբ և ցածր տոկոսադրույքով։',
      image: 'https://www.evoca.am/images-cache/loans/1/17721008940365/560x400.png',
      amount: '30 մլն ֏',
      term: '60 ամիս',
      rate: '9.22%',
      detailsPath: '/hy/loans/fast-business-loan',
    },
    {
      id: 2,
      title: 'Տեքստիլ ոլորտում հումքի ներմուծմանն ուղղված վարկ',
      description: 'Evocabank-ը տրամադրում է բիզնես վարկ՝ տեքստիլ հումքի ներմուծման համար։ Շտապեք դիմել, զարգացնել Ձեր բիզնեսը և դառնալ ոլորտում մրցունակ։',
      image: 'https://www.evoca.am/images-cache/loans/1/17749381045652/415x261.png',
      amount: '500 մլն ֏',
      term: '36 ամիս',
      rate: '8%',
      detailsPath: '/hy/loans/textile-import',
    },
    {
      id: 3,
      title: 'Բիզնես վարկերի վերաֆինանսավորում',
      description: 'Տեղափոխեք Ձեր բիզնես վարկը Evocabank, ստացեք վարկի վերաֆինանսավորում և լրացուցիչ ֆինանսավորում՝ ավելի հարմար պայմաններով։',
      image: 'https://www.evoca.am/images-cache/loans/1/17822121684757/560x400.png',
      amount: '500 մլն ֏',
      term: '120 ամիս',
      rate: '9%',
      detailsPath: '/hy/loans/refinancing',
    },
    {
      id: 4,
      title: 'Պարտատոմսերով ապահովված վարկ',
      description: 'Ստացեք վարկ՝ Բանկի պարտատոմսերի գրավով և շարունակեք զարգացնել Ձեր բիզնեսը։',
      image: 'https://www.evoca.am/images-cache/loans/1/17848707149538/415x261.png',
      amount: '100 մլն ֏',
      term: '36 ամիս',
      rate: '10%',
      detailsPath: '/hy/loans/bond-backed',
    },
    {
      id: 5,
      title: 'Բիզնես վարկ',
      description: 'Զարգացրե\'ք Ձեր բիզնեսը Evocabank-ի հետ փոխշահավետ պայմաններով:',
      image: 'https://www.evoca.am/images-cache/loans/1/16148637167789/415x261.jpg',
      amount: '1 մլրդ ֏',
      term: '10 տարի',
      rate: '6%',
      detailsPath: '/hy/loans/business-loan',
    },
    {
      id: 6,
      title: 'Փոքր և միջին բիզնեսի վարկավորում',
      description: 'Առաջարկում ենք փոքր և միջին բիզնես վարկեր: Լրացրեք Online հայտը և Ձեր անհատական բիզնես խորհրդատուն կապ կհաստատի Ձեզ հետ 1 աշխատանքային օրվա ընթացքում:',
      image: 'https://www.evoca.am/images-cache/loans/1/16148653401062/415x261.jpg',
      amount: '750 մլն ֏',
      term: '84 ամիս',
      rate: '7%',
      detailsPath: '/hy/loans/sme-loans',
    },
    {
      id: 7,
      title: 'Evoca GO',
      description: 'Օգտվեք Եվրոպական Ներդրումային Բանկի (ԵՆԲ) կողմից ֆինանսավորվող ծրագրի շրջանակներում վարկավորման փոխշահավետ հնարավորությունից:',
      image: 'https://www.evoca.am/images-cache/loans/1/1614870243661/415x261.jpg',
      amount: '500 մլն ֏',
      term: '90 ամիս',
      rate: '10.5%',
      detailsPath: '/hy/loans/evoca-go',
    },
    {
      id: 8,
      title: 'Վարկեր ԳՀՀ - Էներգաարդյունավետություն ՓՄՁ-ների համար ծրագիր',
      description: 'Եթե Դուք ցանկանում եք ձեռք բերել ԷԱ սարքավորումներ և մեքենաներ կամ իրականացնել այլ Էներգաարդյունավետ ներդրումներ, այս վարկատեսակը Ձեզ համար է:',
      image: 'https://www.evoca.am/images-cache/loans/1/16148681592638/415x261.jpg',
      amount: '500 մլն ֏',
      term: '5 տարի',
      rate: '9%',
      detailsPath: '/hy/loans/gaf-ee',
    },
    {
      id: 9,
      title: 'Ավանդի գրավով ապահովված վարկ / վարկային սահմանաչափ',
      description: 'Մի՛ օգտագործեք կուտակված խնայողությունները․ Ձեր ֆինանսական խնդիրները կարգավորելու համար մենք ավելի շահավետ տարբերակ ունենք։',
      image: 'https://www.evoca.am/images-cache/loans/1/16148681592638/415x261.jpg',
      amount: '95%',
      term: '36 ամիս',
      rate: '8.5%',
      detailsPath: '/hy/loans/deposit-pledged',
    },
    {
      id: 10,
      title: 'KFW ծրագիր՝ Բիզնեսի կանաչ ֆինանսավորում',
      description: 'Եթե ցանկանում եք իրականացնել Էներգաարդյունավետ և էներգախնայող ներդրումներ բիզնեսի ծախսերը կրճատելու և արդյունավետությունը բարձրացնելու նպատակով, այս ֆինանսավորումը Ձեզ համար է:',
      image: 'https://www.evoca.am/images-cache/loans/1/16142658362632/560x400.png',
      amount: '10 մլն ֏',
      term: '120 ամիս',
      rate: '9.5%',
      detailsPath: '/hy/loans/kfw-green',
    },
    {
      id: 11,
      title: 'Պարզ բիզնես վարկ',
      description: 'Ստացեք Պարզ բիզնես վարկ՝ անշարժ գույքի ապահովմամբ և ցածր տարեկան տոկոսադրույքով: Վարկի տրամադրման վերաբերյալ որոշումը կայացվում է ընդամենը 2-4 աշխատանքային օրվա ընթացքում:',
      image: 'https://www.evoca.am/images-cache/loans/1/16148706367372/415x261.jpg',
      amount: '50 մլն ֏',
      term: '60 ամիս',
      rate: '7.5%',
      detailsPath: '/hy/loans/simple-business-loan',
    },
    {
      id: 12,
      title: 'Հաշվի վարկավորում',
      description: 'Հանդիսանու՞մ եք Evocabank-ի հաշվետեր հաճախորդ առնվազն 1 տարի, ուրեմն Evocabank-ը կօգնի հոգալ Ձեր բիզնեսի ընթացիկ ծախսերը:',
      image: 'https://www.evoca.am/images-cache/loans/1/1614869229831/415x261.jpg',
      amount: '30%',
      term: '180 օր',
      rate: '7%',
      detailsPath: '/hy/loans/account-overdraft',
    },
    {
      id: 13,
      title: 'Վարկային գիծ',
      description: 'Եթե Դուք ունեք կազմակերպություն կամ անհատ ձեռնարկատեր եք և ցանկանում եք մշտապես ունենալ հասանելի վարկային միջոցներ, ապա կարող եք օգտվել Evocabank-ի վերականգնվող և չվերականգնվող վարկային գծերից:',
      image: 'https://www.evoca.am/images-cache/loans/1/16148678149192/415x261.jpg',
      amount: '1.5 մլրդ ֏',
      term: '5 տարի',
      rate: '6%',
      detailsPath: '/hy/loans/credit-line',
    },
    {
      id: 14,
      title: 'Արտադրողականության խթանման ծրագրի ներքո վարկ (գործում է մինչև 31.12.2026թ.)',
      description: 'Մատչելի ֆինանսավորում Ձեր բիզնեսը արդիականացնելու և արտադրողականությունը խթանելու նպատակով:',
      image: 'https://www.evoca.am/images-cache/loans/1/16148665659945/415x261.jpg',
      amount: '1 մլրդ ֏',
      term: '120 ամիս',
      rate: '6%',
      detailsPath: '/hy/loans/productivity-boost',
    },
    {
      id: 15,
      title: 'KFW բանկի կողմից ՄՓՄՁ-ների ֆինանսավորում',
      description: 'Կատարե\'ք Ձեր կապիտալ ներդրումները և իրականացրե\'ք բիզնես գործունեության նպատակները Evocabank-ի հետ:',
      image: 'https://www.evoca.am/images-cache/loans/1/1614869606836/560x400.png',
      amount: '160 մլն ֏',
      term: '60 ամիս',
      rate: '9.5%',
      detailsPath: '/hy/loans/kfw-msme',
    },
  ];

  return (
    <div className="w-full space-y-4">
      {businessLoansData.map((loan) => (
        <BusinessLoanCard key={loan.id} loan={loan} />
      ))}
    </div>
  );
}